configuration = {
	"RESSOURCES_FOLDER": "/data/asevin/experiment/clean_active_nn/",
	"QDB": True,
	"RANDOM": True,
	"SHAPES": [16, 16, 1],
	"INCLUDE_BACKGROUND": True,
	"EVOLUTIVE_SMALL": True,
	"NB_BIASED_EPOCH": 2000,
	"USE_MAIN_WEIGHTS": False,
	"DISPLAY": False,
	"SAVE_PLOT": False,
	"QUERY": 1,
	"BIASED_LR": 0.001,
	"TSM": False,
	"PLTLIM": None,
	"TSM_LIM": None,
	"REDUCE_FACTOR": None,
	"POOL_SIZE": None,
	"MAIN_LR": 0.001,
	"ACTIVATION": "relu",
	"LOSS": "binary_crossentropy",
	"BACKGROUND_SAMPLING": "uncertain",
}
