# .travis.yml
dist: trusty

language: python

python:
    - "2.7.10"

before_install: 'pip install --upgrade pip'

install:
  - pip install -r requirements.txt
  - python setup.py -q install

script:
  - python test_script.py
