configuration = {
	"RESSOURCES_FOLDER": ".",
	"QDB": True,
	"RANDOM": True,
	"SHAPES": [4, 1],
	"INCLUDE_BACKGROUND": True,
	"EVOLUTIVE_SMALL": False,
	"NB_BIASED_EPOCH": 2000,
	"USE_MAIN_WEIGHTS": True,
	"NB_BACKGROUND_POINTS":100,
	"DISPLAY": False,
	"SAVE_PLOT": False,
	"QUERY": 1,
	"BIASED_LR": 0.001,
	"TSM": False,
	"PLTLIM": None,
	"TSM_LIM": None,
	"REDUCE_FACTOR": 2.,
	"POOL_SIZE": None,
	"MAIN_LR": 0.001,
	"ACTIVATION": "relu",
	"LOSS": "binary_crossentropy",
	"BACKGROUND_SAMPLING": "uncertain",
	"NP_SEED":42,
    "TF_SEED":7,
    "SAVING_DIR":".",
    "MAX_ITER":5,
    "LOG_INTO_FILE":False
}
